%% run_key_sensitivity_analysis.m
% Key sensitivity and key-space analysis for the CIS-T-based framework
% This script uses the real CIS-T key-stream generator:
%   generate_chaotic_quence(img, master_key, salt)
%
% It evaluates:
%   1) Correct-key reconstruction
%   2) Ciphertext difference under a one-bit master-key change
%   3) Wrong-key reconstruction quality
%   4) Key-space / parameter-resolution analysis

clear; clc; close all;

%% =========================
% 1. Input image and output directory
% ==========================
img_path = 'photos/house.tiff';
resize_to = [512, 512];

out_dir = 'key_sensitivity_results';
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

original_image = local_read_rgb_uint8(img_path, resize_to);

%% =========================
% 2. DNA encoding rules
% ==========================
dna_complementary_principle = [
    84, 71, 67, 65;
    84, 67, 71, 65;
    71, 84, 65, 67;
    67, 84, 65, 71;
    84, 65, 71, 67;
    71, 65, 84, 67;
    67, 65, 84, 71;
    65, 84, 67, 71;
];
dna_complementary_principle = uint8(dna_complementary_principle);

%% =========================
% 3. Key-space analysis
% ==========================
param_names = {'a', 'm', 'k', 'x0', 'y0', 'hshift'};
precision_digits = [14, 14, 14, 14, 14, 14];
master_key_bits = 128;

keyspace_result = local_keyspace_analysis( ...
    param_names, precision_digits, master_key_bits, out_dir);

%% =========================
% 4. Correct key streams
% ==========================
fprintf('\n===== Generating correct key streams =====\n');

master_key_1 = 'CIST_DNA_STORAGE_KEY_000';
salt_1       = 'DNA_STORAGE_SALT_000';

[key_diff_1, key_scr_1, key_dna_1] = ...
    generate_chaotic_quence(original_image, master_key_1, salt_1);

%% Correct-key encryption
scrambled_1 = scramble_img(original_image, key_scr_1);
diffused_1  = diffuse_img(scrambled_1, key_diff_1);
cipher_1    = encode_img(diffused_1, dna_complementary_principle, key_dna_1);

%% Correct-key reconstruction
decoded_1    = decode_img(cipher_1, dna_complementary_principle, key_dna_1);
dediffused_1 = dediffuse_img(decoded_1, key_diff_1);
recovered_1  = descramble_img(dediffused_1, key_scr_1);

correct_reversible = isequal(original_image, recovered_1);
fprintf('Correct-key reconstruction reversible: %d\n', correct_reversible);

%% =========================
% 5. Perturbed key streams
% ==========================
fprintf('\n===== Generating perturbed key streams =====\n');

% The last characters '0' and '1' differ by one bit in ASCII.
% Therefore, this represents a one-bit perturbation at the master-key level.
master_key_2 = 'CIST_DNA_STORAGE_KEY_001';
salt_2       = salt_1;

[key_diff_2, key_scr_2, key_dna_2] = ...
    generate_chaotic_quence(original_image, master_key_2, salt_2);

mode_used = 'one-bit changed master key';
fprintf('Mode used: %s\n', mode_used);

%% Encrypt the same image using the perturbed key
scrambled_2 = scramble_img(original_image, key_scr_2);
diffused_2  = diffuse_img(scrambled_2, key_diff_2);
cipher_2    = encode_img(diffused_2, dna_complementary_principle, key_dna_2);

%% Wrong-key reconstruction
% The image is encrypted using the correct key, but decoded/decrypted using
% the perturbed key streams.
decoded_wrong    = decode_img(cipher_1, dna_complementary_principle, key_dna_2);
dediffused_wrong = dediffuse_img(decoded_wrong, key_diff_2);
recovered_wrong  = descramble_img(dediffused_wrong, key_scr_2);

%% =========================
% 6. Metrics
% ==========================
% Difference between ciphertexts generated by two one-bit-different keys
[cipher_npcr, cipher_uaci] = local_npcr_uaci(cipher_1, cipher_2);

% Correct-key reconstruction quality
mse_correct  = local_mse(original_image, recovered_1);
psnr_correct = local_psnr(original_image, recovered_1);
ssim_correct = local_ssim_rgb(original_image, recovered_1);

% Wrong-key reconstruction quality
mse_wrong  = local_mse(original_image, recovered_wrong);
psnr_wrong = local_psnr(original_image, recovered_wrong);
ssim_wrong = local_ssim_rgb(original_image, recovered_wrong);

% Ciphertext statistics under the perturbed key
entropy_cipher_1 = local_entropy_uint8(cipher_1);
entropy_cipher_2 = local_entropy_uint8(cipher_2);
[corr_h_1, corr_v_1, corr_d_1] = local_corr_3dir(cipher_1);
[corr_h_2, corr_v_2, corr_d_2] = local_corr_3dir(cipher_2);

%% =========================
% 7. Print results
% ==========================
fprintf('\n========== Key Sensitivity Results ==========\n');
fprintf('Mode used: %s\n', mode_used);
fprintf('Correct-key MSE / PSNR / SSIM: %.6f / %.4f / %.4f\n', ...
    mse_correct, psnr_correct, ssim_correct);
fprintf('Wrong-key MSE / PSNR / SSIM  : %.6f / %.4f / %.4f\n', ...
    mse_wrong, psnr_wrong, ssim_wrong);
fprintf('Cipher NPCR / UACI between two keys: %.4f / %.4f\n', ...
    cipher_npcr, cipher_uaci);
fprintf('Correct-key cipher entropy: %.4f\n', entropy_cipher_1);
fprintf('Perturbed-key cipher entropy: %.4f\n', entropy_cipher_2);
fprintf('Correct-key cipher Corr-H/V/D: %.4f / %.4f / %.4f\n', ...
    corr_h_1, corr_v_1, corr_d_1);
fprintf('Perturbed-key cipher Corr-H/V/D: %.4f / %.4f / %.4f\n', ...
    corr_h_2, corr_v_2, corr_d_2);
fprintf('=============================================\n');

%% =========================
% 8. Save table and images
% ==========================
results = table( ...
    {mode_used}, ...
    {master_key_1}, ...
    {master_key_2}, ...
    {salt_1}, ...
    correct_reversible, ...
    mse_correct, psnr_correct, ssim_correct, ...
    mse_wrong, psnr_wrong, ssim_wrong, ...
    cipher_npcr, cipher_uaci, ...
    entropy_cipher_1, corr_h_1, corr_v_1, corr_d_1, ...
    entropy_cipher_2, corr_h_2, corr_v_2, corr_d_2, ...
    keyspace_result.log2_param_space, ...
    keyspace_result.log2_effective_keyspace, ...
    'VariableNames', { ...
        'Mode', ...
        'Master_Key_1', ...
        'Master_Key_2', ...
        'Salt', ...
        'Correct_Reversible', ...
        'Correct_MSE', 'Correct_PSNR', 'Correct_SSIM', ...
        'WrongKey_MSE', 'WrongKey_PSNR', 'WrongKey_SSIM', ...
        'Cipher_NPCR_percent', 'Cipher_UACI_percent', ...
        'Cipher1_Entropy', 'Cipher1_Corr_H', 'Cipher1_Corr_V', 'Cipher1_Corr_D', ...
        'Cipher2_Entropy', 'Cipher2_Corr_H', 'Cipher2_Corr_V', 'Cipher2_Corr_D', ...
        'ParamResolution_log2', ...
        'EffectiveKeySpace_log2' ...
    } ...
);

csv_path = fullfile(out_dir, 'key_sensitivity_results.csv');
writetable(results, csv_path);

imwrite(original_image, fullfile(out_dir, 'original.png'));
imwrite(uint8(cipher_1), fullfile(out_dir, 'cipher_key_1.png'));
imwrite(uint8(cipher_2), fullfile(out_dir, 'cipher_key_2_one_bit_changed.png'));
imwrite(uint8(recovered_1), fullfile(out_dir, 'recovered_correct_key.png'));
imwrite(uint8(recovered_wrong), fullfile(out_dir, 'recovered_wrong_key.png'));

save(fullfile(out_dir, 'key_sensitivity_workspace.mat'), ...
    'original_image', ...
    'cipher_1', 'cipher_2', ...
    'recovered_1', 'recovered_wrong', ...
    'key_diff_1', 'key_scr_1', 'key_dna_1', ...
    'key_diff_2', 'key_scr_2', 'key_dna_2', ...
    'master_key_1', 'master_key_2', 'salt_1', 'salt_2', ...
    'results', 'keyspace_result');

fprintf('\nResults saved to:\n%s\n', csv_path);


%% ============================================================
% Local helper functions
% ============================================================

function img = local_read_rgb_uint8(img_path, resize_to)
    img = imread(img_path);

    if ndims(img) == 3 && size(img,3) > 3
        img = img(:,:,1:3);
    end

    if ndims(img) == 2
        img = repmat(img, [1, 1, 3]);
    end

    if ~isa(img, 'uint8')
        img = im2uint8(img);
    end

    if ~isempty(resize_to)
        img = imresize(img, resize_to);
    end
end

function H = local_entropy_uint8(img)
    img = uint8(img);
    vals = img(:);
    counts = accumarray(double(vals)+1, 1, [256, 1]);
    p = counts / sum(counts);
    p = p(p > 0);
    H = -sum(p .* log2(p));
end

function [rH, rV, rD] = local_corr_3dir(img)
    img = double(img);

    xH = img(:,1:end-1,:);
    yH = img(:,2:end,:);
    rH = local_corr_vec(xH(:), yH(:));

    xV = img(1:end-1,:,:);
    yV = img(2:end,:,:);
    rV = local_corr_vec(xV(:), yV(:));

    xD = img(1:end-1,1:end-1,:);
    yD = img(2:end,2:end,:);
    rD = local_corr_vec(xD(:), yD(:));
end

function r = local_corr_vec(x, y)
    x = double(x(:));
    y = double(y(:));

    if numel(x) > 50000
        rng(1);
        idx = randperm(numel(x), 50000);
        x = x(idx);
        y = y(idx);
    end

    x = x - mean(x);
    y = y - mean(y);

    denom = sqrt(sum(x.^2) * sum(y.^2));
    if denom == 0
        r = 0;
    else
        r = sum(x .* y) / denom;
    end
end

function [npcr, uaci] = local_npcr_uaci(C1, C2)
    C1 = uint8(C1);
    C2 = uint8(C2);

    diff_pixels = C1 ~= C2;
    npcr = sum(diff_pixels(:)) / numel(C1) * 100;

    uaci = mean(abs(double(C1(:)) - double(C2(:))) / 255) * 100;
end

function mse_val = local_mse(A, B)
    A = double(A);
    B = double(B);
    mse_val = mean((A(:) - B(:)).^2);
end

function psnr_val = local_psnr(A, B)
    mse_val = local_mse(A, B);
    if mse_val == 0
        psnr_val = Inf;
    else
        psnr_val = 10 * log10(255^2 / mse_val);
    end
end

function ssim_val = local_ssim_rgb(A, B)
    A = uint8(A);
    B = uint8(B);

    if exist('ssim', 'file') ~= 2
        ssim_val = NaN;
        return;
    end

    if ndims(A) == 2
        ssim_val = ssim(A, B);
    else
        vals = zeros(1, size(A,3));
        for c = 1:size(A,3)
            vals(c) = ssim(A(:,:,c), B(:,:,c));
        end
        ssim_val = mean(vals);
    end
end

function keyspace_result = local_keyspace_analysis(param_names, precision_digits, master_key_bits, out_dir)
    % Key-space analysis for CIS-T.
    % The parameter-resolution space and the effective master-key search
    % space are reported separately because CIS-T parameters are derived
    % from the master key and are not independent additional secrets.

    if numel(param_names) ~= numel(precision_digits)
        error('param_names and precision_digits must have the same length.');
    end

    num_params = numel(param_names);

    % Parameter-resolution space under numerical precision assumption
    log10_param_space = sum(precision_digits);
    log2_param_space = log10_param_space / log10(2);

    mantissa_param = 10^(log10_param_space - floor(log10_param_space));
    exponent_param = floor(log10_param_space);

    % Effective brute-force complexity governed by the master key
    log2_effective_keyspace = master_key_bits;
    log10_effective_keyspace = master_key_bits * log10(2);

    mantissa_effective = 10^(log10_effective_keyspace - floor(log10_effective_keyspace));
    exponent_effective = floor(log10_effective_keyspace);

    fprintf('\n================ Key Space Analysis for CIS-T ================\n');
    fprintf('Derived CIS-T quantities:\n');
    for i = 1:num_params
        fprintf('  %d) %s, assumed precision: 10^(-%d)\n', ...
            i, param_names{i}, precision_digits(i));
    end

    fprintf('\n[Parameter-resolution space]\n');
    fprintf('Decimal form        : %.4f x 10^%d\n', mantissa_param, exponent_param);
    fprintf('Equivalent in bits  : 2^(%.2f)\n', log2_param_space);

    fprintf('\n[Effective brute-force complexity]\n');
    fprintf('Master key entropy  : %d bits\n', master_key_bits);
    fprintf('Decimal form        : %.4f x 10^%d\n', mantissa_effective, exponent_effective);
    fprintf('Equivalent in bits  : 2^(%.2f)\n', log2_effective_keyspace);

    fprintf('\nNote: The two quantities are reported separately because the CIS-T\n');
    fprintf('parameters are derived from the master key and are not independent\n');
    fprintf('additional secret inputs.\n');

    if log2_effective_keyspace >= 128
        fprintf('Conclusion: The effective key space is sufficient against brute-force search.\n');
    elseif log2_effective_keyspace > 100
        fprintf('Conclusion: The effective key space is generally acceptable, but 128 bits or higher is preferred.\n');
    else
        fprintf('Conclusion: The effective key space may be insufficient.\n');
    end
    fprintf('==============================================================\n');

    % Save parameter settings table
    Parameter = string(param_names(:));
    PrecisionDigits = precision_digits(:);
    StateCountLog10 = precision_digits(:);
    T = table(Parameter, PrecisionDigits, StateCountLog10);

    csv_file = fullfile(out_dir, 'keyspace_parameter_settings_cist.csv');
    writetable(T, csv_file);

    % Save text report
    txt_file = fullfile(out_dir, 'keyspace_analysis_cist.txt');
    fid = fopen(txt_file, 'w');

    fprintf(fid, '================ Key Space Analysis for CIS-T ================\n');
    fprintf(fid, 'Derived CIS-T quantities:\n');
    for i = 1:num_params
        fprintf(fid, '  %d) %s, assumed precision: 10^(-%d)\n', ...
            i, param_names{i}, precision_digits(i));
    end

    fprintf(fid, '\n[Parameter-resolution space]\n');
    fprintf(fid, 'Decimal form        : %.4f x 10^%d\n', mantissa_param, exponent_param);
    fprintf(fid, 'Equivalent in bits  : 2^(%.2f)\n', log2_param_space);

    fprintf(fid, '\n[Effective brute-force complexity]\n');
    fprintf(fid, 'Master key entropy  : %d bits\n', master_key_bits);
    fprintf(fid, 'Decimal form        : %.4f x 10^%d\n', mantissa_effective, exponent_effective);
    fprintf(fid, 'Equivalent in bits  : 2^(%.2f)\n', log2_effective_keyspace);

    fprintf(fid, '\nNote: The two quantities are reported separately because the CIS-T\n');
    fprintf(fid, 'parameters are derived from the master key and are not independent\n');
    fprintf(fid, 'additional secret inputs.\n');

    if log2_effective_keyspace >= 128
        fprintf(fid, 'Conclusion: The effective key space is sufficient against brute-force search.\n');
    elseif log2_effective_keyspace > 100
        fprintf(fid, 'Conclusion: The effective key space is generally acceptable, but 128 bits or higher is preferred.\n');
    else
        fprintf(fid, 'Conclusion: The effective key space may be insufficient.\n');
    end

    fprintf(fid, '==============================================================\n');
    fclose(fid);

    % Save MAT
    keyspace_result = struct();
    keyspace_result.param_names = param_names;
    keyspace_result.precision_digits = precision_digits;
    keyspace_result.log10_param_space = log10_param_space;
    keyspace_result.log2_param_space = log2_param_space;
    keyspace_result.master_key_bits = master_key_bits;
    keyspace_result.log2_effective_keyspace = log2_effective_keyspace;
    keyspace_result.log10_effective_keyspace = log10_effective_keyspace;

    save(fullfile(out_dir, 'keyspace_analysis_cist_workspace.mat'), ...
        'keyspace_result', 'T');

    fprintf('\nKey-space analysis saved to:\n');
    fprintf('  %s\n', txt_file);
    fprintf('  %s\n', csv_file);
end
